### ISSUE TITLE
Remove the already committed *.pyc files

### ISSUE THREAD

**Issue by icyflame** [auviitkgp/fuzzy-control#6]
PYC files won't be committed anymore due to updated gitignore.
Earlier PYC files need to be removed.

attn: @nevinvalsaraj @auviitkgp/embedded-team

**Comment by kshitijgoel007** [comment]
I don't understand. PYC files are necessary to be present in the repo. Can't understand the bug.

**Comment by icyflame** [comment]
This is [utility of a PYC file](http://effbot.org/pyfaq/how-do-i-create-a-pyc-file.htm).

> When a module is imported for the first time, or when the source is more recent than the current compiled file, a .pyc file containing the compiled code will usually be created in the same directory as the .py file.

Also, [see this article on why not to commit pyc files](https://coderwall.com/p/wrxwog/why-not-to-commit-pyc-files-into-git-and-how-to-fix-if-you-already-did)

> Besides that, if a .pyc file exists for a module, it's code can be imported even after deleting the module source file. This may lead to strange bugs in case a user deletes a python module and forgets to delete the .pyc file

As the PYC files can be generated automatically, there's no need to check them into the repo. Apart from that, the danger of the above bug is there.

Why do you think that they are necessary?

**Comment by kshitijgoel007** [comment]
I forgot a question mark :P I was asking, PYC files are necessary?

**Comment by kshitijgoel007** [comment]
But you said that gitignore has been edited such that pyc won't be created
from now.

Issue is resolved right?

**Comment by icyflame** [comment]
Changed the statement a bit!

No, they are not necessary, as they are auto-generated. Also, they will change everytime you change the `py` file, so there's no need to check them into Git, they can be generated on whichever machine the code is being run on.

**Comment by icyflame** [comment]
Yeah, but the existing PYC files need to be deleted. (they were checked
into the repo before the gitignore file was updated)

**Comment by icyflame** [comment]
Fixed in 7b29a750518e4a1283951ff2ec9e500e636a4970
